### ISSUE TITLE
Lost Events / Non responsive REST API

### ISSUE THREAD

**Issue by calderonroberto** [ubc-magic/thingbroker#31]
Sometimes, if a thingBroker server is overloaded (or other unknown factor) the rest API becomes unresponsive, or events are lost to the client. The API becomes unresponsive.

Roberto: replicate.

**Comment by mblackstock** [comment]
Its possible the broker is having problems if lots of things are created, then at least one call is made to the thing for real time events.

When a thing is created, and a client starts listening for real time events on the thing the following resources are allocated:
- a buffer for capturing real time events between calls from the broker.
- a JMS session to the underlying message broker.

The buffer is needed since some events do not persist.

If no real time events are requested from a thing by an application after a long period of time, these resources are deallocated in a clean up call.
Currently we check every 30 seconds, and a buffer life time is 5 minutes.  I will change the buffer/session lifetime to 60 seconds - this should be plenty of time for clients to make another long polling call.  The maximum wait time is now 15 seconds before the poll will return no data.

**Comment by calderonroberto** [comment]
Sounds great. I'll see how it runs.
